steps:
- task: UsePythonVersion@0
  condition: ne(variables['platform'], 'mac-arm64')
  inputs:
    versionSpec: '3.10'
- task: Bash@3
  displayName: 'Run build'
  condition: ne(variables['platform'], 'mac-arm64')
  inputs:
    filePath: $(buildScript)
    arguments: $(buildScriptArgs)
- task: UniversalPackages@0
  displayName: 'Download osx-arm64 package'
  condition: eq(variables['platform'], 'mac-arm64')
  inputs:
    command: download
    vstsFeed: 'Database Systems/azuredatastudio-pgsqltoolsservice'
    vstsFeedPackage: '$(VstsPackageName)'
    vstsPackageVersion: '$(VstsPackageVersion)'
    downloadDirectory: '$(Build.SourcesDirectory)'
- task: ExtractFiles@1
  condition: eq(variables['platform'], 'mac-arm64')
  inputs:
    archiveFilePatterns: '**/*.tar.gz'
    destinationFolder: $(Build.SourcesDirectory)/dist